CREATE DATABASE STD14065642
SELECT * FROM SYSOBJECTS
SELECT NAME FROM SYSOBJECTS WHERE XTYPE = 'U'
SELECT * FROM AUTHORS
SELECT AU_LNAME, STATE FROM AUTHORS
SELECT * FROM AUTHORS WHERE STATE = 'CA'
SELECT * FROM AUTHORS WHERE AU_LNAME = 'White' AND STATE = 'CA'

SELECT * FROM TITLES
SELECT * FROM TITLES WHERE YTD_SALES > 8000
SELECT TITLE, YTD_SALES FROM TITLES WHERE YTD_SALES > 8000
SELECT * FROM TITLES WHERE ROYALTY >= 12 AND ROYALTY <= 24